# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

name: compile pdf

jobs:
  compile-pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.0']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Instalar R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}

      - name: Instalar pacotes
        run: |
          install.packages(c("rmarkdown", "tinytex"))
        shell: Rscript {0}

      - name: Instalar pandoc
        run: sudo apt update && sudo apt install pandoc

      - name: Instalar tinytex
        run: |
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Compilar PDF
        run: |
          rmarkdown::render('artigo.Rmd', encoding = 'UTF-8')
        shell: Rscript {0}

      - name: Commit do PDF
        run: |
          git config --local user.email ${{ secrets.ADMIN_EMAIL }}
          git config --local user.name ${{ secrets.ADMIN_NAME }}
          git add artigo.pdf
          git commit -m 'compilar PDF' || echo "compilar PDF"
          git push origin || echo "compilar PDF"
