# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: compile pdf

jobs:
  compile-pdf:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.2.0']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: artigo.rmd
          output_format: artigo.pdf

      - name: Commit do PDF
        run: |
          git config --local user.email ${{ secrets.ADMIN_EMAIL }}
          git config --local user.name ${{ secrets.ADMIN_NAME }}
          git add artigo.pdf
          git commit -m 'compilar PDF' || echo "compilar PDF"
          git push origin || echo "compilar PDF"
